Constellation-Labs/constellation

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/primitives/CellManager.scala
src/main/scala/org/constellation/primitives/Genesis.scala
src/main/scala/org/constellation/primitives/KeyManager.scala
src/main/scala/org/constellation/primitives/Schema.scala
src/main/scala/org/constellation/serializer/ConstellationKryoRegistrar.scala
src/main/scala/org/constellation/util/Signed.scala
src/main/scala/org/constellation/util/Simulation.scala
src/main/scala/package.scala
src/test/scala/org/constellation/cluster/MultiNodeOEDAGTest.scala

This shouldn't affect anything in V1 flow.  #126

Finalize edge schema and migrate genesis flow over to new schema

---

src/main/scala/org/constellation/crypto/KeyUtils.scala

Remove 0x hex prefix since we switched to B58

---

README.md

Since I had previously PR'ed to master directly, this PR also went to dev* just to avoid later conflicts when dev is merged to dev. Future PR's will exclusively go to dev.
*See https://github.com/Constellation-Labs/constellation/pull/160

Readme update to master.

---

README.md

This only affects markdown files (in particular the readme)
* Fix typos
* Add now static Discord link and resources.
* Add info to folder tree and remove unnecessary details
My first change had been made to master, so I will also push this same change to master* so that there won't be any merge conflict when merging dev to master. Future potential changes will all just go to dev.
Tests formally failing on CircleCI sometimes, but it's just edits to a plaintext markup file.
*See https://github.com/Constellation-Labs/constellation/pull/161

upload some updates that had accumulated

---

src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/datastore/swaydb/SwayDBDatastore.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/main/scala/org/constellation/primitives/RandomTransactionManager.scala
src/main/scala/package.scala

Debug for CPU issues.
Also fix compiler warnings

Try running swaydb on same EC, same for signature request.

---

src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/Genesis.scala
src/main/scala/org/constellation/primitives/PeerManager.scala
src/main/scala/org/constellation/primitives/RandomTransactionManager.scala
src/main/scala/org/constellation/primitives/Schema.scala
src/test/scala/org/constellation/cluster/E2ETest.scala
src/test/scala/org/constellation/cluster/MultiNodeRegisterTest.scala
src/test/scala/org/constellation/consensus/RandomDataTest.scala
src/test/scala/org/constellation/rpc/APIClientTest.scala
src/test/scala/org/constellation/util/TestNode.scala

Updated unit test to cover functionality.

Fixes to download misalignment and changes to peer discovery

---

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/Schema.scala

Adding back the /dashboard endpoint so we can point testnet.constellationlabs.io at new cluster.
@ryle-goehausen Can you double check what I'm doing in the TransactionService to keep track of the last 20 tx?

Adding dashboard functionality back to API.

---

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/util/APIClient.scala
src/test/scala/org/constellation/cluster/E2ETest.scala

Make authPassword private on API and APIClient. Add mutator method

make auth password vars private, add mutator method

---

build.sbt
src/test/scala/org/constellation/cluster/E2ETest.scala

Hoping this with solve the Metaspace OOM issue as well. Seems to on my local box.
See: https://stackoverflow.com/a/47172931/4639271 for more info.

Fork JVM for tests. Recommended when your tests spawn threads.

---

build.sbt
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/Transaction.scala
src/main/scala/org/constellation/primitives/concurrency/MultiLock.scala
src/main/scala/org/constellation/primitives/storage/AddressService.scala
src/main/scala/org/constellation/primitives/storage/CheckpointService.scala
src/main/scala/org/constellation/primitives/storage/MessageService.scala
src/main/scala/org/constellation/primitives/storage/SOEService.scala
src/main/scala/org/constellation/primitives/storage/Storage.scala
src/main/scala/org/constellation/primitives/storage/StorageService.scala
src/main/scala/org/constellation/primitives/storage/TransactionService.scala
src/test/scala/org/constellation/consensus/RandomDataTest.scala
src/test/scala/org/constellation/primitives/concurrency/MultiLockTest.scala
src/test/scala/org/constellation/primitives/storage/AddressServiceTest.scala

This PR contains changes related to the safe-update mechanism (#225) and I've extracted storage services from the EdgeDAO

Safe update for account balances / ledgerApply

---

build.sbt
src/main/scala/org/constellation/ConstellationApp.scala
src/main/scala/org/constellation/datastore/swaydb/SwayDBDatastore.scala
src/main/scala/org/constellation/primitives/Transaction.scala

Some changes required -- they now return all operations in IO.
Kinda weirdly their own IO which is more like a fancy try...

Updating SwayDB to 0.7.

---

src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/util/APIClient.scala

Refactoring of download process (#282)
* Splitting refactoring process into parts
* Wait for peers
* Download majority snapshot block (#236)

Download process refactoring

---

src/main/resources/application.conf
src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/primitives/PeerManager.scala
src/main/scala/org/constellation/util/Metrics.scala
src/test/scala/org/constellation/cluster/E2ETest.scala

This PR covers parallel downloading described in #282 as continuation of PR #286

Download snapshots in parallel

---

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/datastore/swaydb/SwayDbConversions.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/main/scala/org/constellation/primitives/ChannelMessage.scala
src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/Genesis.scala
src/main/scala/org/constellation/primitives/RandomTransactionManager.scala
src/main/scala/org/constellation/primitives/Transaction.scala
src/main/scala/org/constellation/primitives/storage/AcceptedTransactionService.scala
src/main/scala/org/constellation/primitives/storage/AddressService.scala
src/main/scala/org/constellation/primitives/storage/CheckpointService.scala
src/main/scala/org/constellation/primitives/storage/DbStorage.scala
src/main/scala/org/constellation/primitives/storage/SnapshotService.scala
src/main/scala/org/constellation/primitives/storage/Storage.scala
src/main/scala/org/constellation/primitives/storage/StorageService.scala
src/main/scala/org/constellation/primitives/storage/TransactionService.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala
src/main/scala/org/constellation/util/Metrics.scala
src/main/scala/org/constellation/util/ServeUI.scala

Auxiliary databases for snapshots, CBs and TXs

---

src/main/resources/application.conf
src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/primitives/ChannelMessage.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/RandomTransactionManager.scala
src/main/scala/org/constellation/util/Simulation.scala
src/test/scala/org/constellation/cluster/E2ETest.scala

Issue with dropped messages, wrong mempool pull interfering with test, bad hash check on acceptSnapshot (different for single vs. batch,) bad foldLeft with previous vs prvHash. Other fixes.

Fix issues with channel message API / batch endpoint

---

src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/Transaction.scala
src/main/scala/org/constellation/primitives/storage/DbStorage.scala
src/main/scala/org/constellation/primitives/storage/TransactionService.scala
src/test/scala/org/constellation/tx/TXValidationBenchmark.scala

PR prepared as a base for #287

Transaction validation based on NEL

---

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/main/scala/org/constellation/primitives/ChannelMessage.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/RandomTransactionManager.scala
src/main/scala/org/constellation/primitives/Schema.scala
src/test/scala/org/constellation/E2E.scala
src/test/scala/org/constellation/cluster/E2ETest.scala
src/test/scala/org/constellation/tx/TXTests.scala
src/test/scala/org/constellation/util/TestNode.scala

Minor changes re: partitioning setup, not complete but helpful.

Config fixes preparation for light node testing

---

src/main/scala/org/constellation/consensus/CrossTalkConsensus.scala
src/main/scala/org/constellation/consensus/HTTPNodeRemoteSender.scala
src/main/scala/org/constellation/consensus/NodeRemoteSender.scala
src/main/scala/org/constellation/consensus/Round.scala
src/main/scala/org/constellation/consensus/RoundManager.scala
src/main/scala/org/constellation/p2p/routes/BlockBuildingRoundRoute.scala
src/test/scala/org/constellation/consensus/RoundTest.scala

Optimized consensus to broadcast hashes only

---

src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/consensus/Round.scala

Channel messages resolver

---

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/NodeData.scala
src/main/scala/org/constellation/primitives/RandomTransactionManager.scala

This PR is one of incremental changes for #297

Broadcast txs to full node or close light nodes only

---

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/ConstellationNode.scala
src/test/scala/org/constellation/util/TestNode.scala
terraform/default/start

For running locally for testing fixed CLI and added test mode option, also OOM param for debugging cluster

Fix CLI for enabling local runs / add oom option

---

terraform/default/docker-compose.yml
terraform/default/grafana-dashboard/grafana/provisioning/dashboards/constellation-jvm.json
terraform/default/grafana-dashboard/grafana/provisioning/dashboards/dashboard.yml
terraform/default/grafana-dashboard/grafana/provisioning/datasources/datasource.yml
terraform/default/grafana-dashboard/prometheus/prometheus.yml
terraform/default/main.tf
terraform/default/modules/grafana/main.tf
terraform/default/modules/grafana/templates/prometheus.yml.tpl
terraform/default/modules/instance/main.tf
terraform/default/modules/network/main.tf
terraform/default/setup.sh
terraform/default/start

Recommendation is still to copy this and change backend prefix.

Replace default terraform with updated one that launches grafana.

---

build.sbt
src/main/scala/org/constellation/API.scala

hit /buildInfo, get back a response like this
```
{"builtAtMillis":1554161214897,"name":"constellation","scalaVersion":"2.12.8","version":"1.0.12","sbtVersion":"1.2.8","builtAtString":"2019-04-01 23:26:54.897"}
```

Build info endpoint

---

src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/consensus/Round.scala
src/main/scala/org/constellation/consensus/RoundManager.scala
src/main/scala/org/constellation/primitives/ChannelMessage.scala
src/main/scala/org/constellation/primitives/CheckpointFormationManager.scala
src/main/scala/org/constellation/primitives/RandomTransactionManager.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala

#365 - Enabled crosstalk consensus and fixed messages storing. I'll add unit tests in next PR

Turn off old consensus and enable crosstalk one

---

src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/consensus/HTTPNodeRemoteSender.scala
src/main/scala/org/constellation/consensus/Round.scala
src/main/scala/org/constellation/consensus/RoundManager.scala
src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/main/scala/org/constellation/p2p/routes/BlockBuildingRoundRoute.scala
src/main/scala/org/constellation/primitives/RandomTransactionManager.scala
src/main/scala/org/constellation/util/Distance.scala
src/main/scala/org/constellation/util/Partitioner.scala
src/test/scala/org/constellation/consensus/RoundTest.scala
src/test/scala/org/constellation/tx/TXTests.scala

PR is a first step for #343 but also resolves #355

XOR distance and light node for consensus

---

build.sbt
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/consensus/CrossTalkConsensus.scala
src/main/scala/org/constellation/consensus/Round.scala
src/main/scala/org/constellation/consensus/RoundManager.scala
src/main/scala/org/constellation/p2p/DataResolver.scala
src/test/scala/org/constellation/consensus/CrossTalkConsensusTest.scala
src/test/scala/org/constellation/consensus/RoundManagerTest.scala
src/test/scala/org/constellation/consensus/RoundTest.scala

This PR relates to #365, to cover crosstalk consensus flow with unit tests

Crosstalk consensus unit tests

---

src/main/scala/org/constellation/util/Rewards.scala
src/test/scala/org/constellation/util/RewardsTest.scala

Adds explicit case in unit test as well

Add conversion for 0.0 -> 0.0 in entropy calculation

---

src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/storage/AddressService.scala

Isolation for snapshot creation

---

deploy/README.md
src/it/scala/org/constellation/ClusterComputeManualTest.scala
src/it/scala/org/constellation/ClusterHealthCheckTest.scala
src/main/scala/org/constellation/ConfigUtil.scala
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/util/APIClientBase.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala
src/main/scala/org/constellation/util/HealthChecker.scala
src/main/scala/org/constellation/util/Metrics.scala
src/main/scala/org/constellation/util/Simulation.scala
src/test/resources/application.conf
src/test/scala/org/constellation/cluster/E2ETest.scala

Automated cluster state integration test + enhanced healthCheck #406

---

src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/util/Metrics.scala
terraform/default/grafana-dashboard/grafana/provisioning/dashboards/constellation-jvm.json

Adding more dag metrics to prometheus/grafana.
You'll need to remake terraform directories by copying default again (or least copy it's grafana-dashboard folder over to your terraform directory)

Add dag metrics to mwadon3 and default terraform

---

docs-gh-pages/design-choices.md

I corrected some minor spelling and syntax in the documentation.

Correct Spelling and Syntax

---

build.sbt
src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/storage/AcceptedTransactionService.scala
src/main/scala/org/constellation/primitives/storage/AddressService.scala
src/main/scala/org/constellation/primitives/storage/CheckpointService.scala
src/main/scala/org/constellation/primitives/storage/MessageService.scala
src/main/scala/org/constellation/primitives/storage/NotificationService.scala
src/main/scala/org/constellation/primitives/storage/SOEService.scala
src/main/scala/org/constellation/primitives/storage/StorageService.scala
src/main/scala/org/constellation/primitives/storage/TransactionService.scala
src/test/scala/org/constellation/consensus/CrossTalkConsensusTest.scala
src/test/scala/org/constellation/consensus/RoundManagerTest.scala
src/test/scala/org/constellation/consensus/RoundTest.scala
src/test/scala/org/constellation/p2p/PeerAPITest.scala
src/test/scala/org/constellation/primitives/CheckpointBlockValidatorNelTest.scala
src/test/scala/org/constellation/primitives/TipServiceTest.scala
src/test/scala/org/constellation/primitives/storage/CheckpointServiceTest.scala

Also fixed almost all compile warnings.

Change all caches to time-based eviction.

---

deploy/compute/terraform/start-cluster.sh
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/consensus/Round.scala
src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/Genesis.scala
src/main/scala/org/constellation/primitives/Schema.scala
src/main/scala/org/constellation/primitives/TrieBasedTipService.scala
src/main/scala/org/constellation/primitives/storage/CheckpointService.scala
src/main/scala/org/constellation/primitives/storage/DbStorage.scala
src/main/scala/org/constellation/primitives/storage/SOEService.scala
src/main/scala/org/constellation/primitives/storage/TransactionService.scala

Also fix deploy script and temporarily turn off oldDB (block explorer) reference.

Remove old data on accept snapshot, add direct base reference to tip

---

src/main/scala/org/constellation/primitives/PeerManager.scala
src/main/scala/org/constellation/storage/CheckpointService.scala

It just kept growing and growing and growing.

Get rid of memoizedFullData.

---

src/main/scala/org/constellation/consensus/RoundManager.scala

Precaution for dealing with potential actor failures.

Supervisor strategy for stopping failed rounds

---

src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/TrieBasedTipService.scala
src/main/scala/org/constellation/storage/CheckpointService.scala
src/main/scala/org/constellation/storage/SnapshotService.scala
src/main/scala/org/constellation/storage/ThreadSafeSnapshotService.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala
src/main/scala/org/constellation/util/Metrics.scala
src/test/scala/org/constellation/consensus/RandomDataTest.scala
src/test/scala/org/constellation/primitives/CheckpointBlockValidatorNelTest.scala
src/test/scala/org/constellation/primitives/TipServiceTest.scala

Snapshot service properly thread safe

---

src/main/resources/application.conf
src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/primitives/PeerManager.scala
src/main/scala/org/constellation/storage/SnapshotService.scala
src/test/resources/logback-test.xml
src/test/scala/org/constellation/cluster/AppE2ETest.scala
src/test/scala/org/constellation/cluster/E2ETest.scala
src/test/scala/org/constellation/consensus/RoundManagerTest.scala
src/test/scala/org/constellation/consensus/RoundTest.scala
src/test/scala/org/constellation/primitives/TipServiceTest.scala
src/test/scala/org/constellation/storage/CheckpointServiceTest.scala
terraform/buildbox/deploy.sh
terraform/buildbox/main.tf

Unit tests fixes & transaction removal on snapshot acceptance

---

src/main/scala/org/constellation/consensus/Round.scala
src/main/scala/org/constellation/consensus/RoundManager.scala
src/main/scala/org/constellation/storage/TransactionService.scala
src/test/scala/org/constellation/consensus/RoundManagerTest.scala

Move not accepted transactions from InConsensus back to Pending

---

src/main/scala/org/constellation/consensus/Round.scala
src/main/scala/org/constellation/consensus/RoundManager.scala
src/main/scala/org/constellation/primitives/CheckpointBlock.scala
src/main/scala/org/constellation/primitives/concurrency/SingleLock.scala
src/main/scala/org/constellation/storage/AddressService.scala
src/main/scala/org/constellation/storage/SnapshotService.scala
src/main/scala/org/constellation/storage/StorageService.scala
src/main/scala/org/constellation/storage/TransactionService.scala
src/test/resources/logback-test.xml
src/test/scala/org/constellation/cluster/E2ETest.scala

Fix long snapshot creation

---

build.sbt
src/main/scala/org/constellation/primitives/Transaction.scala
src/main/scala/org/constellation/storage/TransactionService.scala
src/main/scala/org/constellation/storage/transactions/PendingTransactionsMemPool.scala
src/main/scala/org/constellation/storage/transactions/TransactionGossiping.scala
src/test/scala/org/constellation/storage/TransactionServiceTest.scala
src/test/scala/org/constellation/storage/transactions/PendingTransactionsMemPoolTest.scala
src/test/scala/org/constellation/storage/transactions/TransactionGossipingTest.scala

Transaction gossiping and transaction service unit tests

---

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/storage/SnapshotService.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala
src/test/scala/org/constellation/cluster/E2ETest.scala
src/test/scala/org/constellation/p2p/PeerAPITest.scala
src/test/scala/org/constellation/storage/SnapshotServiceTest.scala

Fixes "snapshot not found" error as well as writing snapshot to disk

E2E fixes (re: snapshots)

---

src/main/scala/org/constellation/consensus/Round.scala
src/test/scala/org/constellation/consensus/RoundTest.scala

Consensus forward-only

---

src/main/scala/org/constellation/consensus/Round.scala
src/main/scala/org/constellation/primitives/Transaction.scala
src/main/scala/org/constellation/storage/TransactionService.scala
src/main/scala/org/constellation/util/Signature.scala
src/test/scala/org/constellation/consensus/RoundTest.scala
src/test/scala/org/constellation/storage/CheckpointServiceTest.scala

Resolves additional comment #497

497 - create dummy transaction

---

build.sbt
src/main/scala/org/constellation/trust/DataGeneration.scala
src/main/scala/org/constellation/trust/EigenTrust.scala
src/main/scala/org/constellation/util/Rewards.scala
src/test/scala/org/constellation/util/RewardsTest.scala

Port relevant code for rewards to dev for testing Experience service.

Port trust

---

src/main/scala/org/constellation/util/HealthChecker.scala
src/main/scala/org/constellation/util/SnapshotWatcher.scala
src/test/scala/org/constellation/util/HealthCheckerTest.scala

include height when sorting majority state + re-download interval more frequent

---

src/main/scala/org/constellation/consensus/ConsensusWatcher.scala
src/main/scala/org/constellation/domain/observation/ObservationService.scala
src/main/scala/org/constellation/domain/transaction/TransactionGossiping.scala
src/main/scala/org/constellation/p2p/Cluster.scala
src/main/scala/org/constellation/p2p/DataResolver.scala
src/main/scala/org/constellation/primitives/ConcurrentTipService.scala
src/main/scala/org/constellation/primitives/FacilitatorFilter.scala
src/main/scala/org/constellation/primitives/TransactionGenerator.scala
src/main/scala/org/constellation/rollback/RollbackService.scala
src/main/scala/org/constellation/storage/RateLimiting.scala
src/main/scala/org/constellation/storage/external/CloudStorage.scala
src/main/scala/org/constellation/util/HealthChecker.scala
src/main/scala/org/constellation/util/MajorityStateChooser.scala
src/main/scala/org/constellation/util/SnapshotWatcher.scala
src/test/scala/org/constellation/util/HealthCheckerTest.scala

Get rid of implicit Slf4j logger

---

src/main/scala/org/constellation/datastore/SnapshotTrigger.scala
src/main/scala/org/constellation/storage/SnapshotService.scala

Provide messages for SnapshotError

---

src/main/scala/org/constellation/storage/RateLimiting.scala
src/test/scala/org/constellation/storage/RateLimitingTest.scala

Rate limiter

---

src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/domain/transaction/PendingTransactionsMemPool.scala
src/main/scala/org/constellation/domain/transaction/TransactionService.scala
src/main/scala/org/constellation/storage/RateLimiting.scala
src/test/scala/org/constellation/TestHelpers.scala
src/test/scala/org/constellation/domain/transaction/TransactionServiceTest.scala
src/test/scala/org/constellation/storage/RateLimitingTest.scala
src/test/scala/org/constellation/storage/transactions/PendingTransactionsMemPoolTest.scala
src/test/scala/org/constellation/storage/transactions/TransactionGossipingTest.scala

Redefined limits in rate limiter

---

src/test/scala/org/constellation/rollback/RollbackLoaderTest.scala
src/test/scala/org/constellation/rollback/RollbackServiceTest.scala

[Redownload] Ignore rollback tests

---

src/main/resources/application.conf
src/main/scala/org/constellation/datastore/SnapshotTrigger.scala
src/main/scala/org/constellation/rewards/RewardsManager.scala
src/test/resources/application.conf
src/test/scala/org/constellation/consensus/RandomDataTest.scala

[Redownload] Remove snapshotInterval in favor of snapshotHeightInterval

---

src/main/scala/org/constellation/domain/observation/ObservationEvent.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/main/scala/org/constellation/serializer/ConstellationKryoRegistrar.scala
src/main/scala/org/constellation/trust/TrustManager.scala
src/main/scala/package.scala
src/test/scala/org/constellation/rewards/EigenTrustTest.scala

[Redownload] Get rid of SnapshotMisalignment observation

---

src/main/scala/org/constellation/consensus/EdgeProcessor.scala
src/main/scala/org/constellation/domain/snapshotInfo/SnapshotInfoChunk.scala
src/main/scala/org/constellation/p2p/Download.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/main/scala/org/constellation/rollback/RollbackLoader.scala
src/main/scala/org/constellation/rollback/RollbackService.scala
src/main/scala/org/constellation/storage/SnapshotService.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala
src/test/scala/org/constellation/checkpoint/CheckpointBlockValidatorNelTest.scala
src/test/scala/org/constellation/p2p/DownloadProcessTest.scala
src/test/scala/org/constellation/storage/SnapshotServiceTest.scala

[Redownload] Store full snapshot data in SnapshotInfo

---

src/main/scala/org/constellation/p2p/PeerAPI.scala
src/test/scala/org/constellation/p2p/PeerAPITest.scala

[Redownload] Endpoint with all stored snapshots (merge 1st)

---

src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/datastore/SnapshotTrigger.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/test/scala/org/constellation/TestHelpers.scala
src/test/scala/org/constellation/datastore/SnapshotTriggerTest.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala

[Redownload] Base version of redownload service and persist own snapshot if snapshot created (merge 2nd)

---

src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala
src/test/scala/org/constellation/p2p/PeerAPITest.scala

Endpoint for accepted snapshots

---

src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/datastore/SnapshotTrigger.scala
src/main/scala/org/constellation/domain/redownload/MajorityStateChooser.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/util/KeySerializeJSON.scala
src/main/scala/package.scala
src/test/scala/org/constellation/TestHelpers.scala
src/test/scala/org/constellation/datastore/SnapshotTriggerTest.scala
src/test/scala/org/constellation/domain/redownload/MajorityStateChooserTest.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala
src/test/scala/org/constellation/p2p/PeerAPITest.scala

Integrate trust into majority state chooser

---

src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala
src/test/scala/org/constellation/p2p/PeerAPITest.scala

Return stored snapshots from disk only

---

src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/storage/SnapshotService.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala

Download all checkpoints/mempool data beyond Majority Snapshot during re-download 

---

src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/p2p/PeerAPI.scala
src/main/scala/org/constellation/util/CommonEndpoints.scala

Clean endpoints (messages and deprecated)

---

CHANGELOG.md
src/main/scala/org/constellation/p2p/Cluster.scala
src/main/scala/org/constellation/util/Signature.scala
src/regression/scala/org/constellation/SingleHashSignatureTest.scala

Checking signature hash correctness

---

build.sbt
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/infrastructure/endpoints/middlewares/PeerAuthMiddleware.scala
terraform/aws/dag

Redesigned http4s middlewares

---

CHANGELOG.md
src/main/scala/org/constellation/checkpoint/CheckpointAcceptanceService.scala
src/main/scala/org/constellation/checkpoint/CheckpointBlockValidator.scala
src/main/scala/org/constellation/domain/transaction/TransactionValidator.scala
src/regression/scala/org/constellation/TransactionMaxValueTest.scala

Fix validation for many overflowing transactions

---

CHANGELOG.md
src/main/scala/org/constellation/p2p/Cluster.scala

[#1096] Check for highest proposal when leaving

---

src/main/scala/org/constellation/domain/transaction/TransactionChainService.scala
src/main/scala/org/constellation/domain/transaction/TransactionService.scala
src/main/scala/org/constellation/infrastructure/endpoints/TransactionEndpoints.scala
src/main/scala/org/constellation/infrastructure/p2p/client/TransactionClientInterpreter.scala
src/test/scala/org/constellation/domain/transaction/TransactionChainServiceTest.scala
src/test/scala/org/constellation/infrastructure/endpoints/TransactionEndpointsTest.scala

[#993] Add endpoint returning ref to the last transaction for a given address

---

CHANGELOG.md
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/rewards/RewardsManager.scala
src/main/scala/org/constellation/storage/AddressService.scala

Rewards adjusted to 4 snapshots per minute. Reward metrics.

---

CHANGELOG.md
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/domain/p2p/PeerHealthCheck.scala
src/main/scala/org/constellation/domain/p2p/client/ClusterClientAlgebra.scala
src/main/scala/org/constellation/infrastructure/endpoints/ClusterEndpoints.scala
src/main/scala/org/constellation/infrastructure/p2p/PeerHealthCheckWatcher.scala
src/main/scala/org/constellation/infrastructure/p2p/client/ClusterClientInterpreter.scala
src/main/scala/org/constellation/p2p/Cluster.scala
src/test/scala/org/constellation/domain/p2p/PeerHealthCheckTest.scala

Dead peers

---

CHANGELOG.md
src/main/scala/org/constellation/checkpoint/CheckpointAcceptanceService.scala
src/main/scala/org/constellation/consensus/ConsensusManager.scala
src/main/scala/org/constellation/domain/redownload/DownloadService.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/storage/SnapshotService.scala
src/test/scala/org/constellation/domain/redownload/DownloadServiceTest.scala
terraform/aws/dag

Accept buffer pool after (re)download

---

CHANGELOG.md
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/storage/MessageService.scala
src/main/scala/org/constellation/storage/SnapshotService.scala

Resolves #1223 
Resolves #1224

Data migration fix and channel storage disabled

---

CHANGELOG.md
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/domain/p2p/PeerHealthCheck.scala
src/main/scala/org/constellation/p2p/Cluster.scala
src/main/scala/org/constellation/primitives/Schema.scala
src/main/scala/org/constellation/storage/SnapshotService.scala

Disallow offline nodes for communication

---

CHANGELOG.md
src/main/scala/org/constellation/trust/SelfAvoidingWalk.scala
src/main/scala/org/constellation/trust/TrustManager.scala

Fix self avoiding walk - missing edges and negative 0d

---

CHANGELOG.md
src/main/scala/org/constellation/util/HealthChecker.scala

No active tips issue

---

CHANGELOG.md
src/main/scala/org/constellation/domain/p2p/PeerHealthCheck.scala
src/test/scala/org/constellation/domain/p2p/PeerHealthCheckTest.scala

Dead peer cache

---

CHANGELOG.md
src/main/scala/org/constellation/consensus/Consensus.scala
src/main/scala/org/constellation/consensus/ConsensusManager.scala
src/test/scala/org/constellation/TestHelpers.scala
src/test/scala/org/constellation/consensus/ConsensusManagerTest.scala

Still about to test it on the cluster, hence -> Draft
Resolves #697

[#697] Fix union checkpoint block creation during consensus

---

build.sbt
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/domain/cloud/CloudService.scala
src/main/scala/org/constellation/domain/cloud/config/CloudConfig.scala
src/main/scala/org/constellation/domain/cloud/providers/CloudServiceProvider.scala
src/main/scala/org/constellation/domain/cloud/providers/GCPProvider.scala
src/main/scala/org/constellation/domain/cloud/providers/LocalProvider.scala
src/main/scala/org/constellation/domain/cloud/providers/S3Provider.scala
src/main/scala/org/constellation/domain/configuration/CliConfig.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/infrastructure/configuration/CliConfigParser.scala
src/main/scala/org/constellation/primitives/EdgeDAO.scala
src/main/scala/org/constellation/primitives/Genesis.scala
src/test/scala/org/constellation/TestHelpers.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala

Support for cloud providers and queue sending

---

CHANGELOG.md
src/main/scala/org/constellation/domain/cloud/CloudService.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala

Remove snapshot only if snapshot was send to cloud

---

CHANGELOG.md
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/CustomDirectives.scala
src/main/scala/org/constellation/domain/configuration/NodeConfig.scala
src/main/scala/org/constellation/domain/p2p/client/SignClientAlgebra.scala
src/main/scala/org/constellation/infrastructure/endpoints/SignEndpoints.scala
src/main/scala/org/constellation/infrastructure/endpoints/middlewares/PeerAuthMiddleware.scala
src/main/scala/org/constellation/infrastructure/p2p/PeerResponse.scala
src/main/scala/org/constellation/infrastructure/p2p/client/SignClientInterpreter.scala
src/main/scala/org/constellation/p2p/Cluster.scala
src/main/scala/org/constellation/serializer/ConstellationKryoRegistrar.scala
src/main/scala/org/constellation/session/Registration.scala
terraform/aws/dag

Remove IP from whitelisting

---

CHANGELOG.md
src/main/scala/org/constellation/API.scala
src/main/scala/org/constellation/ConstellationNode.scala
src/main/scala/org/constellation/domain/configuration/NodeConfig.scala
src/main/scala/org/constellation/p2p/Cluster.scala
src/main/scala/org/constellation/primitives/NodeData.scala
terraform/aws/dag

Include alias in cluster/info.

Add possibility to set alias for node in whitelisting file.

---

CHANGELOG.md
build.sbt
keytool/src/main/scala/org/constellation/keytool/KeyStoreUtils.scala
keytool/src/main/scala/org/constellation/keytool/cert/SelfSignedCertificate.scala
src/main/scala/org/constellation/ConstellationNode.scala
wallet/src/main/scala/org/constellation/wallet/Wallet.scala

This reverts commit 8ecb6a8be00f455adb2fbc404565290e8e641854.

Revert "[#1252] Adjust KeyStoreUtils to reuse functionality in comakery-hot-wallet"

---

CHANGELOG.md
src/main/scala/org/constellation/domain/cloud/CloudService.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala

Gaps in cloud queue fixed by calculating diff between majority and already sent

---

CHANGELOG.md
src/main/scala/org/constellation/checkpoint/CheckpointAcceptanceService.scala
src/main/scala/org/constellation/checkpoint/CheckpointService.scala
src/main/scala/org/constellation/domain/consensus/ConsensusService.scala
src/main/scala/org/constellation/primitives/Genesis.scala
src/main/scala/org/constellation/storage/AddressService.scala
src/main/scala/org/constellation/storage/SOEService.scala
src/main/scala/org/constellation/storage/SnapshotService.scala
src/main/scala/org/constellation/storage/StorageService.scala
src/test/scala/org/constellation/storage/AddressServiceTest.scala

Use proper locks everywhere in AddressService

Clear whole AddressService before applying Snapshot during redownload/rollback.

---

CHANGELOG.md
keytool/src/main/scala/org/constellation/keytool/CliConfig.scala
keytool/src/main/scala/org/constellation/keytool/KeyStoreUtils.scala
keytool/src/main/scala/org/constellation/keytool/KeyTool.scala
keytool/src/main/scala/org/constellation/keytool/KeyUtils.scala
src/test/scala/org/constellation/crypto/KeyTest.scala
src/test/scala/org/constellation/util/wallet/KeyToolTest.scala

Possibility to export private key from KeyStore in hexadecimal format

---

CHANGELOG.md
src/main/scala/org/constellation/domain/consensus/ConsensusService.scala
src/main/scala/org/constellation/infrastructure/endpoints/TransactionEndpoints.scala
src/main/scala/org/constellation/storage/PendingMemPool.scala
src/test/scala/org/constellation/domain/transaction/TransactionServiceTest.scala
src/test/scala/org/constellation/infrastructure/endpoints/TransactionEndpointsTest.scala

Query transactions by source address

---

CHANGELOG.md
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala

Download only last majority snaphsot

---

CHANGELOG.md
build.sbt
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala

Fix for downloading last majority snapshot

---

CHANGELOG.md
src/main/scala/org/constellation/domain/transaction/TransactionService.scala
src/main/scala/org/constellation/storage/PendingMemPool.scala
src/main/scala/org/constellation/storage/StorageService.scala
src/main/scala/org/constellation/storage/algebra/StorageAlgebra.scala

Additional metrics for non-dummy transactions

---

CHANGELOG.md
src/main/scala/org/constellation/checkpoint/CheckpointAcceptanceService.scala
src/test/scala/org/constellation/checkpoint/CheckpointAcceptanceServiceTest.scala

Validate that transactions form a correct chain

---

CHANGELOG.md
build.sbt
wallet/src/main/scala/org/constellation/wallet/BIP44.scala
wallet/src/main/scala/org/constellation/wallet/TransactionDataConciseFormat.scala
wallet/src/test/scala/org/constellation/wallet/BIP44Test.scala
wallet/src/test/scala/org/constellation/wallet/TransactionDataConciseFormatTest.scala

Add concise transaction data format and bip44 reference implementations

---

CHANGELOG.md
src/main/scala/org/constellation/checkpoint/CheckpointService.scala
src/main/scala/org/constellation/consensus/ConsensusManager.scala
src/main/scala/org/constellation/domain/consensus/ConsensusService.scala
src/main/scala/org/constellation/storage/AddressService.scala
src/main/scala/org/constellation/storage/ConcurrentStorageService.scala
src/main/scala/org/constellation/storage/MessageService.scala
src/main/scala/org/constellation/storage/SOEService.scala
src/main/scala/org/constellation/storage/StorageService.scala

Objects in mem-pool no longer expire after some time

---

.github/workflows/integration_tests.yml
build.sbt
integration-tests/src/test/resources/scripts/join.sh
integration-tests/src/test/resources/scripts/start.sh
integration-tests/src/test/resources/scripts/stop.sh
integration-tests/src/test/resources/test.conf
integration-tests/src/test/scala/org/constellation/DownloadSpec.scala
integration-tests/src/test/scala/org/constellation/TestConfig.scala
integration-tests/src/test/scala/org/constellation/TransactionsProcessingSpec.scala
integration-tests/src/test/scala/org/constellation/schema/ClusterNode.scala
integration-tests/src/test/scala/org/constellation/schema/HostPort.scala
integration-tests/src/test/scala/org/constellation/schema/LatestMajorityHeight.scala
integration-tests/src/test/scala/org/constellation/schema/NodeStateInfo.scala
integration-tests/src/test/scala/org/constellation/testutils/CustomMatchers.scala
integration-tests/src/test/scala/org/constellation/testutils/HttpUtil.scala
integration-tests/ssh-config
terraform/aws/dag

Integration tests, scenario #2

---

CHANGELOG.md
src/main/scala/org/constellation/checkpoint/CheckpointAcceptanceService.scala
src/main/scala/org/constellation/domain/transaction/TransactionService.scala
src/test/scala/org/constellation/domain/transaction/TransactionServiceTest.scala

Pending transactions that no longer can be accepted are removed

---

src/main/scala/org/constellation/gossip/sampling/GossipPath.scala
src/main/scala/org/constellation/gossip/state/GossipMessage.scala
src/main/scala/org/constellation/infrastructure/p2p/BinaryCodec.scala
src/main/scala/org/constellation/serialization/ConstellationKryoRegistrar.scala

There's no task created for this issue

Gossip message binary encoding

---

schema/src/main/scala/org/constellation/schema/serialization/SchemaKryoRegistrar.scala
schema/src/main/scala/org/constellation/schema/snapshot/HeightRange.scala
schema/src/main/scala/org/constellation/schema/snapshot/LatestMajorityHeight.scala
schema/src/main/scala/org/constellation/schema/snapshot/MajorityInfo.scala
schema/src/main/scala/org/constellation/schema/snapshot/SnapshotProposalPayload.scala
src/main/resources/application.conf
src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/domain/p2p/client/SnapshotClientAlgebra.scala
src/main/scala/org/constellation/domain/redownload/MajorityStateChooser.scala
src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/gossip/GossipService.scala
src/main/scala/org/constellation/gossip/bisect/package.scala
src/main/scala/org/constellation/gossip/snapshot/SnapshotProposalGossipService.scala
src/main/scala/org/constellation/gossip/state/GossipMessage.scala
src/main/scala/org/constellation/gossip/validation/MessageValidator.scala
src/main/scala/org/constellation/infrastructure/endpoints/SnapshotEndpoints.scala
src/main/scala/org/constellation/infrastructure/p2p/client/SnapshotClientInterpreter.scala
src/main/scala/org/constellation/invertedmap/InvertedMap.scala
src/main/scala/org/constellation/p2p/Cluster.scala
src/main/scala/org/constellation/serialization/ConstellationKryoRegistrar.scala
src/main/scala/org/constellation/snapshot/SnapshotTrigger.scala
src/test/scala/org/constellation/TestHelpers.scala
src/test/scala/org/constellation/datastore/SnapshotTriggerTest.scala
src/test/scala/org/constellation/domain/redownload/MajorityStateChooserTest.scala
src/test/scala/org/constellation/domain/redownload/MissingProposalFinderTest.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala
src/test/scala/org/constellation/gossip/bisect/BisectTest.scala
src/test/scala/org/constellation/invertedmap/InvertedMapTest.scala

Resolves #1464 and ~~likely~~ #1465 ~~(to be confirmed)~~

Fetch missing proposals

---

build.sbt
schema/src/main/scala/org/constellation/schema/Id.scala
schema/src/main/scala/org/constellation/schema/signature/HashSignature.scala
schema/src/main/scala/org/constellation/schema/signature/Signed.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/gossip/validation/MessageValidator.scala
src/main/scala/org/constellation/infrastructure/endpoints/SnapshotEndpoints.scala
src/test/scala/org/constellation/infrastructure/endpoints/SnapshotEndpointsTest.scala

Snapshot proposal signature validation

---

src/main/scala/org/constellation/DAO.scala
src/main/scala/org/constellation/gossip/GossipService.scala
src/main/scala/org/constellation/gossip/snapshot/SnapshotProposalGossipService.scala
src/main/scala/org/constellation/gossip/state/GossipMessagePathTracker.scala

There's no task for this issue

Gossip metrics

---

src/main/resources/application.conf
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/main/scala/org/constellation/gossip/GossipService.scala
src/main/scala/org/constellation/gossip/sampling/PartitionerPeerSampling.scala

There's no task for this issue

Gossip recovery flow fix

---

schema/src/main/scala/org/constellation/schema/snapshot/HeightRange.scala
src/main/resources/application.conf
src/main/resources/logback-prod.xml
src/main/scala/org/constellation/domain/redownload/MissingProposalFinder.scala
src/main/scala/org/constellation/domain/redownload/RedownloadService.scala
src/test/scala/org/constellation/domain/redownload/RedownloadServiceTest.scala

Log level change is for the @TheMMaciek request

Fix lookup range for missing proposals

---

CHANGELOG.md
keytool/src/main/scala/org/constellation/keytool/Base58.scala
src/main/scala/org/constellation/domain/transaction/TransactionValidator.scala
src/test/scala/org/constellation/domain/transaction/TransactionValidatorTest.scala

Better transaction validation
